# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitledd.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import os
dir = os.getcwd()

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(281, 161)
        Dialog.setStyleSheet(u"background-color: rgb(54, 57, 63);")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(40, 20, 91, 23))

        self.pushButton.clicked.connect(self.audio)

        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(40, 60, 91, 23))

        self.pushButton_2.clicked.connect(self.three)

        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(40, 100, 91, 23))

        self.pushButton_3.clicked.connect(self.four)

        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Dialog)
        self.pushButton_4.setGeometry(QtCore.QRect(160, 60, 91, 23))

        self.pushButton_4.clicked.connect(self.ten)

        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(Dialog)
        self.pushButton_5.setGeometry(QtCore.QRect(160, 20, 91, 23))

        self.pushButton_5.clicked.connect(self.seven)

        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(Dialog)
        self.pushButton_6.setGeometry(QtCore.QRect(160, 100, 91, 23))

        self.pushButton_6.clicked.connect(self.highest)
    
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName("pushButton_6")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        global r
    def audio(self):
        global c
        c = 1
        r = "Audio"
        with open(dir + "\\val.dat", 'w') as f:
            f.write(str(c) + "`" + r)
    def three(self):
        c = 3
        r = "360p"
        with open(dir + "\\val.dat", 'w') as f:
            f.write(str(c) + "`" + r)
    def four(self):
        c = 3
        r = "480p"
        with open(dir + "\\val.dat", 'w') as f:
            f.write(str(c) + "`" + r)
    def seven(self):
        c = 3
        r = "720p"
        with open(dir + "\\val.dat", 'w') as f:
            f.write(str(c) + "`" + r)
    def ten(self):
        c = 3
        r = "1080p"
        with open(dir + "\\val.dat", 'w') as f:
            f.write(str(c) + "`" + r)
    def highest(self):
        c = 5
        r = "highest"
        with open(dir + "\\val.dat", 'w') as f:
            f.write(str(c) + "`" + r)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Resolution"))
        Dialog.setStatusTip(_translate("Dialog", "Select Resolution"))
        self.pushButton.setText(_translate("Dialog", "Audio"))
        self.pushButton_2.setText(_translate("Dialog", "360p"))
        self.pushButton_3.setText(_translate("Dialog", "480p"))
        self.pushButton_4.setText(_translate("Dialog", "1080p"))
        self.pushButton_5.setText(_translate("Dialog", "720p"))
        self.pushButton_6.setText(_translate("Dialog", "Highest Quality"))
        

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    app.setStyle('fusion')
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
